n = int(input('Quer saber a tabuada de um número? É só digitar: '))
#print('{}x1={}'.format(n,n*1))
#print('{}x2={}'.format(n,n*2))
#print('{}x3={}'.format(n,n*3))
#print('{}x4={}'.format(n,n*4))
#print('{}x5={}'.format(n,n*5))
#print('{}x6={}'.format(n,n*6))
#print('{}x7={}'.format(n,n*7))
#print('{}x8={}'.format(n,n*8))
#print('{}x9={}'.format(n,n*9))
#print('{}x10={}'.format(n,n*10))
print('-' * 12)
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 3, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x {:2} = {}'.format(n, 10, n*10))
print('-' * 12)

